---
 - hosts: web
   sudo: yes
   tasks:
    - name: upgrade all packages
      yum: name=* state=latest
    - yum: name=vim state=latest
    # EPEL/Remi/RPMforgeをインストールする
    - yum: name={{item}} state=present 
      with_items:
        - epel-release
#         - http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
#         - http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
        - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    # 明示的に指定したいのでenabledは全て0にする
    - replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *= *1" replace="enabled=0"
      with_items:
        - epel.repo
        #- rpmforge.repo
        - remi.repo
    - name: install nginx rpm
      yum: name=http://nginx.org/packages/centos/7/x86_64/RPMS/nginx-1.10.0-1.el7.ngx.x86_64.rpm state=present
    - name: start nginx and enabled
      service: name=nginx state=started enabled=yes
    - name: install php packages
      yum: name={{item}} enablerepo=remi,epel state=present
      with_items:
       - php
       - php-fpm
       - php-pear
       - php-devel
       - php-mbstring
       - php-pdo
       - php-mysql
       - php-gd
       - php-xdebug
      notify:
       - restart nginx
    - name: install mysql
      yum: name=http://dev.mysql.com/get/mysql-community-release-el7-7.noarch.rpm state=present
      notify:
       - start mysql
    - name: install composer
      become: true
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin && mv /usr/bin/composer.phar /usr/bin/composer
         creates=/usr/bin/composer
   handlers:
    - name: restart nginx
      service: name=nginx state=restarted enabled=yes #enabled=yes 自動起動
    - name: start mysql
      service: name=mysqld state=started enabled=yes
    #- name: mysql set password
    #  command: mysqladmin -u root password "{{ mysql_root_pw }}"
    - name: stop firewalld
      service: name=firewalld state=stop
